
CREATE SCHEMA SEISMIC_DB.SILVER;


CREATE OR REPLACE VIEW SEISMIC_DB.SILVER.EARTHQUAKE_EVENTS3_VIEW AS
SELECT
    BUNID,
    BSOURCE_ID,
    BSOURCE_CATALOG,
    BFLYNN_REGION,
    BLAT,
    BLON,
    BDEPTH,
    BEVTYPE,
    BAUTH,
    BMAG,
    BMAGTYPE,
    BACTION,
    UNID,
    SOURCE_ID,
    SOURCE_CATALOG,
    TO_TIMESTAMP(TO_NUMBER(LASTUPDATE) / 1000000) AS LASTUPDATE_UTC,
    TO_TIMESTAMP(TO_NUMBER(TIME) / 1000000) AS EVENT_TIME_UTC,
    FLYNN_REGION,
    LAT,
    LON,
    DEPTH,
    EVTYPE,
    AUTH,
    MAG,
    MAGTYPE,
    ACTION,
    TO_TIMESTAMP(TO_NUMBER(RECEIVED_AT) / 1000000) AS RECEIVED_AT_UTC,
    SOURCE_DB,
    SOURCE_TABLE,
    OPERATION,
    TO_TIMESTAMP_NTZ(LOAD_TIMESTAMP / 1000) AS LOAD_TIMESTAMP_UTC
FROM SEISMIC_DB.BRONZE.EARTHQUAKE_EVENTS3;



SELECT * FROM SEISMIC_DB.SILVER.EARTHQUAKE_EVENTS3_VIEW;